Add Rstudio addin for package
wlandau/targetsketch pull request #14
Opened 2022-09-03 15:37 UTC by parmsam

# Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targetsketch/blob/main/CODE_OF_CONDUCT.md).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targetsketch/blob/main/CONTRIBUTING.md).
* [x] I have already submitted an issue to the [issue tracker](http://github.com/wlandau/targetsketch/issues) to discuss my idea with the maintainer.

# Summary

Please explain the purpose and scope of your contribution.

* Adds in RStudio Addin for targetsketch::targetsketch() using dcf file.
* Updated News.md

# Related GitHub issues and pull requests

* Ref: #8 

# Checklist

* [x] This pull request is not a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests).

2022-09-07 19:41 UTC, wlandau requested changes
Looks good, my inline comments are minor.

2022-09-07 19:41 UTC, wlandau commented on inst/rstudio/addins.dcf
> +Interactive: true
Would you add a newline at the end of the file?

2022-09-07 19:41 UTC, wlandau commented on R/server.R
> +      visNetwork::visNetworkProxy("graph") |>
The native pipe requires R >= 4.1.0. Would you update the `DESCRIPTION` file to reflect this?

2022-09-07 19:41 UTC, wlandau commented on R/ui.R
> +              "Reset",
With the growing number of buttons, we may need to be more specific in the titles: for example, "Reset selection".

2022-09-07 19:41 UTC, wlandau commented on R/server.R
> +    input$reset,{
If I click "Reset" with nothing selected, I get an error:

```r
# A tibble: 0 × 2
# … with 2 variables: name <chr>, command <chr>
# ℹ Use `colnames()` to see all variable names
# A tibble: 0 × 2
# … with 2 variables: name <chr>, command <chr>
# ℹ Use `colnames()` to see all variable names
Warning: Error in data.frame: arguments imply differing number of rows: 0, 1
[No stack trace available]
```

2022-09-07 22:09 UTC, parmsam commented on R/ui.R
> +              "Reset",
Changed button label to Reset selection.

2022-09-07 22:09 UTC, parmsam commented on R/server.R
> +      visNetwork::visNetworkProxy("graph") |>
Done.

2022-09-07 22:09 UTC, parmsam commented on inst/rstudio/addins.dcf
> +Interactive: true
Added.

2022-09-07 22:10 UTC, parmsam commented on R/server.R
> +    input$reset,{
It should allow you to click reset with nothing selected now.

2022-09-08 13:46 UTC, wlandau approved these changes

2022-09-08 13:55 UTC, wlandau commented
This PR also has lints: https://github.com/wlandau/targetsketch/runs/8250736793?check_suite_focus=true#step:7:15

2022-09-08 20:13 UTC, wlandau commented
By the way, you can lint locally with `lintr::lint_package()`. The `targetsketch` `.lintr` file might not be up to date with the new version of `lintr`. `targets` uses this one: https://github.com/ropensci/targets/blob/main/.lintr

2022-09-09 13:03 UTC, wlandau commented
Looks like there are merge conflicts with the other PR. Would you resolve them?

2022-09-09 15:15 UTC, merged