Add copy button
wlandau/targetsketch pull request #17
Opened 2022-09-06 19:28 UTC by parmsam

# Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targetsketch/blob/main/CODE_OF_CONDUCT.md).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targetsketch/blob/main/CONTRIBUTING.md).
* [x] I have already submitted an issue to the [issue tracker](http://github.com/wlandau/targetsketch/issues) to discuss my idea with the maintainer.

# Summary

Please explain the purpose and scope of your contribution.

Add button to copy _targets.R code to clipboard.

# Related GitHub issues and pull requests

* Ref: #15

# Checklist

* [x] This pull request is not a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests).

2022-09-07 19:27 UTC, wlandau requested changes
Looks really good. My comments are minor.

2022-09-07 19:27 UTC, wlandau commented on DESCRIPTION
> +    rclipboard
It's a little thing, but would you re-alphabetize the packages and restore the indentation to 2 spaces?

2022-09-07 19:27 UTC, wlandau commented on R/ui.R
> +            uiOutput("clip")
Would you write `shiny::` in front of `uiOutput()`.

2022-09-07 19:27 UTC, wlandau commented on R/ui.R
> +            uiOutput("clip")
Also, it looks like the copy button is on a new row. Would be great to have the control buttons on the same row.

2022-09-07 19:42 UTC, wlandau commented
Also, feel free to add yourself to the `DESCRIPTION` as a contributor. Example: https://github.com/ropensci/targets/blob/4f44c7729dcbd215977e8c3ebc9c077ac4e23295/DESCRIPTION#L30-L36

2022-09-07 21:51 UTC, parmsam commented on DESCRIPTION
> +    rclipboard
Should be resolved now.

2022-09-07 21:52 UTC, parmsam commented on R/ui.R
> +            uiOutput("clip")
Sounds good. Using shiny:div() to get buttons on same row.

2022-09-08 13:44 UTC, wlandau approved these changes
Looks great, thanks for the PR.

2022-09-08 20:17 UTC, merged