Add script argument into targetsketch()
wlandau/targetsketch pull request #28
Opened 2022-10-09 23:43 UTC by parmsam

# Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targetsketch/blob/main/CODE_OF_CONDUCT.md).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targetsketch/blob/main/CONTRIBUTING.md).
* [x] I have already submitted an issue to the [issue tracker](http://github.com/wlandau/targetsketch/issues) to discuss my idea with the maintainer.

# Summary

Please explain the purpose and scope of your contribution.

- Fixes #27
- Adds script arg into targetsketch() where user can specify 

# Related GitHub issues and pull requests

* Ref: #27

# Checklist

* [x] This pull request is not a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests).

2022-10-10 13:09 UTC, wlandau requested changes

2022-10-10 13:09 UTC, wlandau commented on R/api.R
> +#' @param script path of reference _targets.R script
I would prefer to first state the type of the argument: character of length 1 for an existing script and `NULL` to use the default starting script. Also would be good to begin with a capital letter and end with a period.

2022-10-10 13:09 UTC, wlandau commented on R/ui.R
> +ui <- function(path) {
Could we name this argument `script` to stay internally consistent?

2022-10-10 13:09 UTC, wlandau commented on R/utils.R
> +  } else if (file.exists(path) && grepl("_targets.R", path)) {
The target script need not be named `_targets.R`: https://books.ropensci.org/targets/projects.html, https://docs.ropensci.org/targets/reference/tar_make.html#arguments. (NB `basename()` would be more dependable for checking a specific name).

2022-10-10 13:09 UTC, wlandau commented on R/utils.R
> +    message("_targets.R file does not exist at specified path")
Might be good to call it the target script file in this first line of the message.

2022-10-10 13:09 UTC, wlandau commented on R/utils.R
> +    cat()
Is this a debugging statement?

2022-10-10 13:09 UTC, wlandau commented on R/utils.R
> +    message("_targets.R file does not exist at specified path")
Unless... do we really need these messages?

2022-10-10 13:09 UTC, wlandau commented on R/api.R
> +#' @param script path of reference _targets.R script
Also would be good to add a complete set of assertions on the script. If it isn't `NULL`, then it should be a character, it should have length 1, it should be a nonempty string (check with `nzchar()`), and the file path should exist.

2022-10-10 13:09 UTC, wlandau commented on R/utils.R
> +    message("_targets.R file does not exist at specified path")
We can move this assertion to the top-level user-side `targetsketch()` function.

2022-10-10 13:12 UTC, wlandau commented on R/api.R
> +#' @param script path of reference _targets.R script
If the script file does not exist, I think it would be better to quit `targetsketch()` with an informative error and not launch the app. `NULL` covers the case when there is no script.

2022-10-11 00:35 UTC, parmsam commented on R/ui.R
> +ui <- function(path) {
Will do. Thanks!

2022-10-11 00:37 UTC, parmsam commented on R/utils.R
> +  } else if (file.exists(path) && grepl("_targets.R", path)) {
Got it. I'll remote that check from the condition.

2022-10-11 02:07 UTC, parmsam commented on R/api.R
> +#' @param script path of reference _targets.R script
Sounds good. Updated api.R accordingly.

2022-10-11 02:09 UTC, parmsam commented on R/utils.R
> +    message("_targets.R file does not exist at specified path")
Done.

2022-10-11 02:09 UTC, parmsam commented on R/utils.R
> +    cat()
Changed this up a little so it's more clear.

2022-10-11 14:57 UTC, wlandau approved these changes

2022-10-11 14:57 UTC, merged